version: "3"
services:
  elasticsearch:
    build: ./elasticsearch
    networks:
      - elk_net
    ports:
      - 9200:9200
  
  logstash:
    build: ./logstash
    networks:
      - elk_net
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline/

  filebeat:    
    networks:
      - elk_net
    volumes:
      - ./filebeat/filebeat-test.yml:/usr/share/filebeat/filebeat.yml
      - ./sample-log-path:/usr/share/filebeat/logs/sample-log-path
    build: ./filebeat

networks:
  elk_net: